# Generated by Django 3.2.8 on 2021-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Mobile_Number', models.BigIntegerField()),
                ('College_Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Last_Modified', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
