# Generated by Django 3.2.8 on 2021-10-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_regform_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regform',
            old_name='fname',
            new_name='First_Name',
        ),
    ]
